In [1]:
import numpy as np

In [ ]:
sin = opp/hyp
cos = adj/hyp
tan = opp/adj >> sin/cos 
cosec = hyp/opp >> 1/sin
sec   = hyp/adj >> 1/cos
cot   = adj/opp >>1/tan >> cos/sin

In [ ]:
sin(30) = 1/2 

# functions 

In [ ]:
np.sin()
np.cos()
np.tan()

In [ ]:
Unit of angle is degree or radian 

# sin

In [2]:
np.sin(30)

-0.9880316240928618

In [3]:
np.pi = 180 degree

3.141592653589793

In [5]:
sin_30 = np.sin(np.pi/6)  # pi/6 = 30 degree
sin_30

0.49999999999999994

In [6]:
# sin_45 = 1/sqrt(2)
sin_45 = np.sin(np.pi/4) # pi/4 = 45 degree
sin_45

0.7071067811865476

In [7]:
np.sqrt(2)

1.4142135623730951

In [8]:
1/np.sqrt(2)

0.7071067811865475

In [9]:
sin_60 = np.sin(np.pi/3) # pi/3 = 60 degree
sin_60

0.8660254037844386

In [10]:
sin_90 = np.sin(np.pi/2) # pi/2 = 90 degree
sin_90

1.0

In [11]:
np.sin(90)

0.8939966636005579

# 2. cos 

In [13]:
np.cos(np.pi/6)

0.8660254037844387

In [14]:
np.cos(np.pi/2)

6.123233995736766e-17

In [15]:
np.cos(np.pi/4)

0.7071067811865476

# tan 

In [17]:
np.tan(np.pi/6)

0.5773502691896257

In [18]:
np.tan(np.pi/4)

0.9999999999999999

In [20]:
np.tan(np.pi/3)

1.7320508075688767

In [21]:
np.tan(np.pi/2)

1.633123935319537e+16

# deg2rad

In [22]:
np.pi/2  # 90

1.5707963267948966

In [23]:
np.pi/4 # 45

0.7853981633974483

In [ ]:
np.pi/4 # 50

In [24]:
np.deg2rad(45)

0.7853981633974483

In [25]:
np.deg2rad(90)

1.5707963267948966

In [26]:
np.deg2rad(50)

0.8726646259971648

In [27]:
np.deg2rad(55)

0.9599310885968813

In [28]:
np.deg2rad(15)

0.2617993877991494

In [29]:
np.sin(np.deg2rad(15))

0.25881904510252074

In [30]:
np.sin(np.deg2rad(30))

0.49999999999999994

In [31]:
deg = np.array([0,30,45,60,90])
deg

array([ 0, 30, 45, 60, 90])

In [32]:
np.deg2rad(deg)

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [33]:
sin_arr = np.sin(np.deg2rad(deg))
sin_arr

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [34]:
sin_arr = np.around(np.sin(np.deg2rad(deg)))
sin_arr

array([0., 0., 1., 1., 1.])

In [35]:
sin_arr = np.around(np.sin(np.deg2rad(deg)),2)
sin_arr

array([0.  , 0.5 , 0.71, 0.87, 1.  ])

In [37]:
cosec_arr = np.around(1/np.sin(np.deg2rad(deg)),2)
cosec_arr

C:\Users\Shridhar\AppData\Local\Temp\ipykernel_8952\998784478.py:1: RuntimeWarning: divide by zero encountered in divide
  cosec_arr = np.around(1/np.sin(np.deg2rad(deg)),2)


array([ inf, 2.  , 1.41, 1.15, 1.  ])

# radian to degree

In [39]:
radian = np.array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])
radian

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [40]:
np.rad2deg(radian)

array([ 0.        , 30.00000025, 44.99999981, 59.99999993, 90.00000018])

In [41]:
np.around(np.rad2deg(radian))

array([ 0., 30., 45., 60., 90.])