# np.sum()

In [3]:
import numpy as np
arr = np.array([2,3,4,5,6])
np.sum(arr)

20

# np.cumsum()

In [5]:
arr = np.array([2,3,4,5,6])
np.cumsum(arr)

array([ 2,  5,  9, 14, 20])

In [6]:
arr = np.random.ranf(10)
arr

array([0.12046635, 0.47574217, 0.07553165, 0.30671021, 0.5812356 ,
       0.48994048, 0.65538262, 0.22495861, 0.6841218 , 0.20962977])

In [7]:
np.cumsum(arr)

array([0.12046635, 0.59620851, 0.67174016, 0.97845037, 1.55968597,
       2.04962645, 2.70500908, 2.92996768, 3.61408948, 3.82371925])

In [8]:
np.sum(arr)

3.823719252925052

In [9]:
arr = np.random.randint(1,10, size=(2,2))
arr

array([[7, 5],
       [3, 6]])

In [10]:
np.cumsum(arr)

array([ 7, 12, 15, 21])

In [11]:
arr = np.random.randint(1,10, size=(2,2,2))
arr

array([[[9, 6],
        [7, 1]],

       [[6, 6],
        [2, 2]]])

In [12]:
np.cumsum(arr)

array([ 9, 15, 22, 23, 29, 35, 37, 39])

In [13]:
np.sum(arr)

39

# argmax()

In [ ]:
It will return the index of max value 

In [14]:
arr = np.random.randint(11,100, size=20)
arr

array([26, 79, 46, 59, 97, 97, 37, 54, 74, 12, 47, 91, 98, 79, 51, 42, 27,
       56, 66, 95])

In [15]:
np.max(arr)

98

In [16]:
np.argmax(arr)

12

In [17]:
arr[12]

98

In [18]:
arr = np.random.randint(11,100, size=(2,5))
arr

array([[85, 35, 84, 68, 19],
       [60, 47, 71, 29, 74]])

In [19]:
np.max(arr)

85

In [20]:
np.argmax(arr)

0

In [23]:
arr = np.random.randint(11,100, size=(2,5))
arr

array([[48, 80, 74, 16, 53],
       [81, 49, 18, 90, 36]])

In [24]:
np.max(arr)

90

In [25]:
np.argmax(arr)

8

In [26]:
np.argmax(arr, axis=0)

array([1, 0, 0, 1, 0], dtype=int64)

In [27]:
np.argmax(arr, axis=1)

array([1, 3], dtype=int64)

In [28]:
arr = np.random.randint(11,100, size=(10,5))
arr

array([[20, 75, 81, 30, 60],
       [80, 71, 32, 46, 23],
       [59, 23, 75, 32, 21],
       [58, 11, 69, 45, 43],
       [67, 46, 20, 65, 75],
       [25, 46, 63, 80, 50],
       [50, 21, 21, 92, 89],
       [27, 40, 41, 16, 71],
       [42, 73, 71, 37, 41],
       [52, 89, 89, 82, 70]])

In [29]:
np.argmax(arr, axis=0)

array([1, 9, 9, 6, 6], dtype=int64)

In [30]:
np.argmax(arr, axis=1)

array([2, 0, 2, 2, 4, 3, 3, 4, 1, 1], dtype=int64)

# Null Values 

In [32]:
np.nan

nan

In [33]:
arr = np.array([6,7,8,4,np.nan,4,5,6,7])
arr

array([ 6.,  7.,  8.,  4., nan,  4.,  5.,  6.,  7.])

In [34]:
a
arr

array([ 6.,  7.,  8.,  4., nan,  4.,  5.,  6., nan])

# Null Values Count 

In [36]:
np.isnan(arr)

array([False, False, False, False,  True, False, False, False,  True])

In [37]:
np.isnan(arr).sum()

2

# Count non zero Values 

In [39]:
np.count_nonzero(arr)

9

In [40]:
len(arr)

9

In [41]:
arr

array([ 6.,  7.,  8.,  4., nan,  4.,  5.,  6., nan])

In [43]:
arr = np.array([ 6,  7,  0,  0, np.nan,  4,  5,  6, np.nan])

In [44]:
arr

array([ 6.,  7.,  0.,  0., nan,  4.,  5.,  6., nan])

In [45]:
np.count_nonzero(arr)

7

# np.repeat()

In [ ]:
np.repeat(value, shape )

In [48]:
np.full(7,4)

array([4, 4, 4, 4, 4, 4, 4])

In [49]:
np.repeat(7,4)

array([7, 7, 7, 7])

In [50]:
np.repeat(7,(4,2))

ValueError: operands could not be broadcast together with shape (1,) (2,)

In [51]:
np.repeat(10,4)

array([10, 10, 10, 10])

In [52]:
np.repeat(5,20)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

# np.delete

In [ ]:
this will delete the specified value with help index 
Syntax: 
    np.delete(arr, index_pos)

In [54]:
arr 

array([ 6.,  7.,  0.,  0., nan,  4.,  5.,  6., nan])

In [55]:
np.delete(arr,1)

array([ 6.,  0.,  0., nan,  4.,  5.,  6., nan])

In [56]:
np.delete(arr,1)

array([ 6.,  0.,  0., nan,  4.,  5.,  6., nan])

In [57]:
np.delete(arr,5)

array([ 6.,  7.,  0.,  0., nan,  5.,  6., nan])

In [59]:
arr_new = np.delete(arr,[0,5])
arr_new

array([ 7.,  0.,  0., nan,  5.,  6., nan])

In [61]:
arr

array([ 6.,  7.,  0.,  0., nan,  4.,  5.,  6., nan])

In [62]:
arr_new = np.delete(arr,np.where(arr > 5))
arr_new

array([ 0.,  0., nan,  4.,  5., nan])